---
  - debug:
      msg: 
       - '{{ ansible_distribution_release }}'
  
  ## INSTALL ZABBIX-AGENT
  
  - name: Instalando Zabbix Agent para Amazon
    yum:
      name: "{{ url_agent_amazonna }}"
      state: present
    when: 
     - ansible_distribution_release == "NA" 
     - zabbix_agent_install
  
  - name: Instalando Zabbix Agent 2 v6 para Amazon
    yum:
      name: "{{ url_agent2_v6_amazonna }}"
      state: present
    ignore_errors: True
    when: 
     - ansible_distribution_release == "NA" 
     - zabbix_agent2_install and zabbix_version is version_compare('6.0', '>=')

  - name: Instalando Zabbix Agent 2 para Amazon
    yum:
      name: "{{ url_agent2_amazonna }}"
      state: present
    ignore_errors: True
    when: 
     - ansible_distribution_release == "NA" 
     - zabbix_agent2_install
     - zabbix_version is version_compare('5.0', '>=') and zabbix_version is version_compare('6.0', '<')
  
  ## UPDATE ZABBIX-AGENT
  
  - name: Update Zabbix Agent para Amazon 
    yum:
       name: "{{ url_agent_amazonna }}"
       state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_release == "NA"
     - zabbix_agent_update
  
  - name: Update Zabbix Agent 2 v6 para Amazon
    yum:
      name: "{{ url_agent2_v6_amazonna }}"
      state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_version == "NA"
     - zabbix_agent2_update and zabbix_version is version_compare('6.0', '>=')
  
  - name: Update Zabbix Agent para Amazon
    yum:
      name: "{{ url_agent2_amazonna }}"
      state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_version == "NA"
     - zabbix_agent2_update
     - zabbix_version is version_compare('5.0', '>=') and zabbix_version is version_compare('6.0', '<')