---
  - debug:
      msg: 
       - '{{ ansible_distribution_version }}'
  
  ## INSTALL ZABBIX-AGENT

  - name: Instalando Zabbix Agent para Amazon 2
    yum:
      name: "{{ url_agent_amazonna2 }}"
      state: present
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent_install
  
  - name: Instalando Zabbix Agent 2 v6 para Amazon 2
    yum:
      name: "{{ url_agent2_v6_amazonna2 }}"
      state: present
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent2_install and zabbix_version is version_compare('6.0', '>=')

  - name: Instalando Zabbix Agent para Amazon 2
    yum:
      name: "{{ url_agent2_amazonna2 }}"
      state: present
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent2_install 
     - zabbix_version is version_compare('5.0', '>=') and zabbix_version is version_compare('6.0', '<')
  
  # UPDATE ZABBIX-AGENT
  
  - name: Update Zabbix Agent para Amazon 2
    yum:
      name: "{{ url_agent_amazonna2 }}"
      state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent_update

  - name: Update Zabbix Agent 2 v6 para Amazon 2
    yum:
      name: "{{ url_agent2_v6_amazonna2 }}"
      state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent2_update and zabbix_version is version_compare('6.0', '>=')
  
  - name: Update Zabbix Agent para Amazon 2
    yum:
      name: "{{ url_agent2_amazonna2 }}"
      state: latest
    ignore_errors: True
    when: 
     - ansible_distribution_version == "2"
     - zabbix_agent2_update 
     - zabbix_version is version_compare('5.0', '>=') and zabbix_version is version_compare('6.0', '<')