---
    - name: user zabbix in visudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'zabbix ALL=NOPASSWD: ALL'
        
    - name: Instalando Zabbix Agent
      yum:
        name: "{{ url_agent_centos7 }}"
        state: present
        lock_timeout : 180

    - name: 
      yum:
        name: epel-release
        enablerepo: extras
        state: present
        lock_timeout : 180

    - name: Aplicando config do Zabbix
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - Restart Zabbix Agent

    - name: Iniciar Zabbix no boot
      service:
        name: zabbix-agent
        enabled: yes
