---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Dependencias
  apt:
    name:
      - gpg
    state: present

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Ubuntu"
  with_items:
    - deb-src
    - deb

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Debian"
  with_items:
    - deb-src
    - deb

## INSTALL ZABBIX-AGENT

- name: Install Zabbix-agent
  apt:
    name: zabbix-agent
    state: present
  when: zabbix_agent_install

- name: Install Zabbix-agent2
  apt:
    name: zabbix-agent2
    state: present
  when:
   - zabbix_agent2_install and zabbix_version is version_compare('5.0', '>=')

## UPDATE ZABBIX-AGENT

- name: Update Zabbix-agent
  apt:
    name: zabbix-agent
    state: latest
  when: zabbix_agent_update 

- name: Update Zabbix-agent2
  apt:
    name: zabbix-agent2
    state: latest
  when:
   - zabbix_agent2_update and zabbix_version is version_compare('5.0', '>=')
