---
- include_tasks: RedHat.yml
  when: 
   - ansible_distribution_file_variety == 'RedHat'
   - ansible_distribution != "Amazon"

- include_tasks: "{{ ansible_distribution }}.yml"
  when: ansible_distribution  == "Amazon"

- include_tasks: Debian.yml
  when: ansible_distribution_file_variety == 'Debian'