---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
    
- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install Zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
  when: zabbix_agent_install

- name: Install Zabbix-agent2
  yum:
    name: zabbix-agent2
    state: latest
  when:
   - zabbix_agent2_install 
   - zabbix_version >= 5.0

- name: Update Zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
  when: zabbix_agent_update 

- name: Update Zabbix-agent2
  yum:
    name: zabbix-agent2
    state: latest
  when:
   - zabbix_agent2_update
   - zabbix_version >= 5.0

- name: user zabbix in visudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'zabbix ALL=NOPASSWD: ALL'
        
- name: Aplicando config do Zabbix-agentd
  template:
   src: zabbix_agentd.conf.j2
   dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - Restart Zabbix Agent
  when: zabbix_agent_update or zabbix_agent_install

- name: Aplicando config do Zabbix-agent2
  template:
   src: zabbix_agent2.conf.j2
   dest: /etc/zabbix/zabbix_agent2.conf
  notify:
    - Restart Zabbix Agent2
  when:
   - zabbix_agent2_update or zabbix_agent2_install
   - zabbix_version >= 5.0

- name: Iniciar Zabbix no boot
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  when: zabbix_agent_update or zabbix_agent_install

- name: Iniciar Zabbix-agent2 no boot
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  when:
   - zabbix_agent2_update or zabbix_agent2_install
   - zabbix_version >= 5.0

  

