---
    - name: user zabbix in visudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'zabbix ALL=NOPASSWD: ALL'
        
    - name: Instalando Zabbix Agent
      apt:
        deb: "{{ url_agent_ubuntu16 }}"

    - name: Aplicando config do Zabbix
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - Restart Zabbix Agent

    - name: Iniciar Zabbix com sistema
      service:
        name: zabbix-agent
        enabled: yes
