---
    - name: Start Zabbix Agent
      service:
        name: zabbix-agent
        state: started

    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted