---
zabbix_hostname: "{{ ansible_hostname }}"
zabbix_hostmetadata: 'os-linux'
url_agent_centos6: "http://repo.zabbix.com/zabbix/4.4/rhel/6/x86_64/zabbix-agent-4.4.10-1.el6.x86_64.rpm"
url_agent_centos7: "http://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-agent-4.4.10-1.el7.x86_64.rpm"
url_agent_amazonna: "http://repo.zabbix.com/zabbix/4.4/rhel/6/x86_64/zabbix-agent-4.4.10-1.el6.x86_64.rpm"
url_agent_amazonna2: "https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent2-5.0.9-1.el7.x86_64.rpm"
url_agent_ubuntu18: "http://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix/zabbix-agent_4.4.10-1%2Bbionic_amd64.deb"
url_agent_ubuntu16: "http://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix/zabbix-agent_4.4.10-1%2Bxenial_amd64.deb"
url_agent_debian9: "http://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix/zabbix-agent_4.4.10-1%2Bstretch_amd64.deb"
url_agent_debian7: "http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix/zabbix-agent_3.4.9-1%2Bwheezy_amd64.deb"
url_agent_ubuntu20: "http://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix/zabbix-agent_4.4.10-1%2Bfocal_amd64.deb"